# Enable the repo's "Sponsor" button by uncommenting a line and filling it in.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
# github: [vikast908]
# ko_fi: your_handle
# custom: ["https://your-donate-url"]
