#!/usr/bin/env python3
"""Regenerate a dependency lock for Writing Agent from the *installed* environment.

`pyproject.toml` is the canonical declaration of dependencies; this tool resolves their
full closure (direct + transitive) against what's actually installed and prints exact pins.
Unlike a bare `pip freeze`, it walks only the project's declared dependency tree, so an
environment that also has unrelated packages (a shared/dev venv) doesn't pollute the lock,
and the project's own editable install is excluded.

Run it in a CLEAN virtualenv that installed the project from *public PyPI* - the pins are
only as resolvable as the environment they're read from:

    python -m venv .venv && . .venv/bin/activate     # or .venv\\Scripts\\activate on Windows
    pip install -e ".[dev,headroom]"                 # add deep,web to lock those extras too
    python scripts/gen_lock.py > requirements.lock.txt

Optional deps that aren't installed are reported on stderr and simply omitted (e.g. the
git-only `scrapo`, or `playwright` when the `deep` extra wasn't installed).
"""
from __future__ import annotations

import argparse
import importlib.metadata as md
import sys
from pathlib import Path

from packaging.requirements import Requirement

_ROOT = Path(__file__).resolve().parents[1]
_PYPROJECT = _ROOT / "pyproject.toml"


def _load_pyproject() -> dict:
    try:
        import tomllib  # Python 3.11+
    except ModuleNotFoundError:  # 3.10
        try:
            import tomli as tomllib  # type: ignore
        except ModuleNotFoundError:
            sys.exit("Need Python 3.11+ (tomllib) or `pip install tomli` to parse pyproject.toml.")
    with open(_PYPROJECT, "rb") as f:
        return tomllib.load(f)


def _norm(name: str) -> str:
    return name.lower().replace("_", "-")


def _seed_requirements(data: dict, extras: list[str]) -> list[str]:
    proj = data.get("project", {})
    seeds: list[str] = list(proj.get("dependencies", []))
    optional = proj.get("optional-dependencies", {})
    for group in extras:
        seeds += optional.get(group, [])
    return seeds


def closure(seeds: list[str], self_name: str) -> tuple[list[str], list[str]]:
    """Return (sorted "Name==version" lines, missing seed names). Evaluates environment
    markers; skips requirements gated on an extra we didn't request."""
    resolved: dict[str, tuple[str, str]] = {}
    missing: list[str] = []
    seen: set[str] = set()
    stack = list(seeds)
    while stack:
        raw = stack.pop()
        try:
            req = Requirement(raw)
        except Exception:  # noqa: BLE001 - a bare name with no specifiers/markers
            req = None
        name = req.name if req else raw.strip()
        key = _norm(name)
        if req is not None and req.marker is not None:
            # Skip deps that don't apply to this environment or need an unrequested extra.
            try:
                if not req.marker.evaluate({"extra": ""}):
                    continue
            except Exception:  # noqa: BLE001 - undefined marker variable -> treat as N/A
                continue
        if key in seen or key == _norm(self_name):
            continue
        seen.add(key)
        try:
            dist = md.distribution(name)
        except md.PackageNotFoundError:
            missing.append(name)
            continue
        resolved[key] = (dist.metadata["Name"], dist.version)
        for dep in (dist.requires or []):
            stack.append(dep)
    lines = [f"{nm}=={ver}" for _, (nm, ver) in sorted(resolved.items())]
    return lines, sorted(set(missing))


def main() -> None:
    ap = argparse.ArgumentParser(description="Regenerate the dependency lock from the installed env.")
    ap.add_argument("--extras", default="dev,headroom",
                    help="Comma-separated optional-dependency groups to include "
                         "(default: dev,headroom; add deep,web to lock those too).")
    args = ap.parse_args()

    data = _load_pyproject()
    self_name = data.get("project", {}).get("name", "writing-agent")
    extras = [e.strip() for e in args.extras.split(",") if e.strip()]
    seeds = _seed_requirements(data, extras)
    lines, missing = closure(seeds, self_name)

    print(f"# Dependency lock - generated by scripts/gen_lock.py (extras: {', '.join(extras) or 'none'}).")
    print("# Regenerate in a CLEAN venv installed from public PyPI; pyproject.toml is canonical.")
    for line in lines:
        print(line)
    if missing:
        print(f"note: {len(missing)} declared dep(s) not installed, omitted: "
              f"{', '.join(missing)}", file=sys.stderr)


if __name__ == "__main__":
    main()
